// Code generated by protoc-gen-go. DO NOT EDIT.
// source: InnerMsg.proto

package innermsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Head struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cmd                  uint32   `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	TransTypes           int32    `protobuf:"varint,3,opt,name=transTypes,proto3" json:"transTypes,omitempty"`
	MsgType              uint32   `protobuf:"varint,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	SSerId               int32    `protobuf:"varint,5,opt,name=sSerId,proto3" json:"sSerId,omitempty"`
	SSerType             int32    `protobuf:"varint,6,opt,name=sSerType,proto3" json:"sSerType,omitempty"`
	DSerId               int32    `protobuf:"varint,7,opt,name=dSerId,proto3" json:"dSerId,omitempty"`
	DSerType             int32    `protobuf:"varint,8,opt,name=dSerType,proto3" json:"dSerType,omitempty"`
	TypeName             string   `protobuf:"bytes,9,opt,name=typeName,proto3" json:"typeName,omitempty"`
	Sflow                int32    `protobuf:"varint,10,opt,name=sflow,proto3" json:"sflow,omitempty"`
	Dflow                int32    `protobuf:"varint,11,opt,name=dflow,proto3" json:"dflow,omitempty"`
	SIp                  string   `protobuf:"bytes,12,opt,name=sIp,proto3" json:"sIp,omitempty"`
	GameId               int32    `protobuf:"varint,13,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{0}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Head) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Head) GetTransTypes() int32 {
	if m != nil {
		return m.TransTypes
	}
	return 0
}

func (m *Head) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Head) GetSSerId() int32 {
	if m != nil {
		return m.SSerId
	}
	return 0
}

func (m *Head) GetSSerType() int32 {
	if m != nil {
		return m.SSerType
	}
	return 0
}

func (m *Head) GetDSerId() int32 {
	if m != nil {
		return m.DSerId
	}
	return 0
}

func (m *Head) GetDSerType() int32 {
	if m != nil {
		return m.DSerType
	}
	return 0
}

func (m *Head) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Head) GetSflow() int32 {
	if m != nil {
		return m.Sflow
	}
	return 0
}

func (m *Head) GetDflow() int32 {
	if m != nil {
		return m.Dflow
	}
	return 0
}

func (m *Head) GetSIp() string {
	if m != nil {
		return m.SIp
	}
	return ""
}

func (m *Head) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type NetHead struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cmd                  uint32   `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	GameId               uint32   `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Flag                 string   `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Code                 uint32   `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Ext                  string   `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetHead) Reset()         { *m = NetHead{} }
func (m *NetHead) String() string { return proto.CompactTextString(m) }
func (*NetHead) ProtoMessage()    {}
func (*NetHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{1}
}

func (m *NetHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetHead.Unmarshal(m, b)
}
func (m *NetHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetHead.Marshal(b, m, deterministic)
}
func (m *NetHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetHead.Merge(m, src)
}
func (m *NetHead) XXX_Size() int {
	return xxx_messageInfo_NetHead.Size(m)
}
func (m *NetHead) XXX_DiscardUnknown() {
	xxx_messageInfo_NetHead.DiscardUnknown(m)
}

var xxx_messageInfo_NetHead proto.InternalMessageInfo

func (m *NetHead) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *NetHead) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *NetHead) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *NetHead) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *NetHead) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NetHead) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NetHead) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

type MsgBody struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBody) Reset()         { *m = MsgBody{} }
func (m *MsgBody) String() string { return proto.CompactTextString(m) }
func (*MsgBody) ProtoMessage()    {}
func (*MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{2}
}

func (m *MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBody.Unmarshal(m, b)
}
func (m *MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBody.Marshal(b, m, deterministic)
}
func (m *MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBody.Merge(m, src)
}
func (m *MsgBody) XXX_Size() int {
	return xxx_messageInfo_MsgBody.Size(m)
}
func (m *MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBody proto.InternalMessageInfo

func (m *MsgBody) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MsgBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ClientBody struct {
	Head                 *NetHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBody) Reset()         { *m = ClientBody{} }
func (m *ClientBody) String() string { return proto.CompactTextString(m) }
func (*ClientBody) ProtoMessage()    {}
func (*ClientBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{3}
}

func (m *ClientBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBody.Unmarshal(m, b)
}
func (m *ClientBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBody.Marshal(b, m, deterministic)
}
func (m *ClientBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBody.Merge(m, src)
}
func (m *ClientBody) XXX_Size() int {
	return xxx_messageInfo_ClientBody.Size(m)
}
func (m *ClientBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBody.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBody proto.InternalMessageInfo

func (m *ClientBody) GetHead() *NetHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ClientBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type InnerMsgForDB struct {
	PreCmd               int32    `protobuf:"varint,1,opt,name=preCmd,proto3" json:"preCmd,omitempty"`
	PreSid               int32    `protobuf:"varint,2,opt,name=preSid,proto3" json:"preSid,omitempty"`
	PreStp               int32    `protobuf:"varint,3,opt,name=preStp,proto3" json:"preStp,omitempty"`
	PreFlow              int32    `protobuf:"varint,4,opt,name=preFlow,proto3" json:"preFlow,omitempty"`
	Uid                  int32    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Cmd                  int32    `protobuf:"varint,6,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Body                 []byte   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMsgForDB) Reset()         { *m = InnerMsgForDB{} }
func (m *InnerMsgForDB) String() string { return proto.CompactTextString(m) }
func (*InnerMsgForDB) ProtoMessage()    {}
func (*InnerMsgForDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{4}
}

func (m *InnerMsgForDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMsgForDB.Unmarshal(m, b)
}
func (m *InnerMsgForDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMsgForDB.Marshal(b, m, deterministic)
}
func (m *InnerMsgForDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMsgForDB.Merge(m, src)
}
func (m *InnerMsgForDB) XXX_Size() int {
	return xxx_messageInfo_InnerMsgForDB.Size(m)
}
func (m *InnerMsgForDB) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMsgForDB.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMsgForDB proto.InternalMessageInfo

func (m *InnerMsgForDB) GetPreCmd() int32 {
	if m != nil {
		return m.PreCmd
	}
	return 0
}

func (m *InnerMsgForDB) GetPreSid() int32 {
	if m != nil {
		return m.PreSid
	}
	return 0
}

func (m *InnerMsgForDB) GetPreStp() int32 {
	if m != nil {
		return m.PreStp
	}
	return 0
}

func (m *InnerMsgForDB) GetPreFlow() int32 {
	if m != nil {
		return m.PreFlow
	}
	return 0
}

func (m *InnerMsgForDB) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InnerMsgForDB) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *InnerMsgForDB) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type RegDispatch struct {
	IRet                 int32    `protobuf:"varint,1,opt,name=iRet,proto3" json:"iRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegDispatch) Reset()         { *m = RegDispatch{} }
func (m *RegDispatch) String() string { return proto.CompactTextString(m) }
func (*RegDispatch) ProtoMessage()    {}
func (*RegDispatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{5}
}

func (m *RegDispatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegDispatch.Unmarshal(m, b)
}
func (m *RegDispatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegDispatch.Marshal(b, m, deterministic)
}
func (m *RegDispatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegDispatch.Merge(m, src)
}
func (m *RegDispatch) XXX_Size() int {
	return xxx_messageInfo_RegDispatch.Size(m)
}
func (m *RegDispatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RegDispatch.DiscardUnknown(m)
}

var xxx_messageInfo_RegDispatch proto.InternalMessageInfo

func (m *RegDispatch) GetIRet() int32 {
	if m != nil {
		return m.IRet
	}
	return 0
}

type RegDispatchRes struct {
	IRet                 int32    `protobuf:"varint,1,opt,name=iRet,proto3" json:"iRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegDispatchRes) Reset()         { *m = RegDispatchRes{} }
func (m *RegDispatchRes) String() string { return proto.CompactTextString(m) }
func (*RegDispatchRes) ProtoMessage()    {}
func (*RegDispatchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b62ec459e15f753, []int{6}
}

func (m *RegDispatchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegDispatchRes.Unmarshal(m, b)
}
func (m *RegDispatchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegDispatchRes.Marshal(b, m, deterministic)
}
func (m *RegDispatchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegDispatchRes.Merge(m, src)
}
func (m *RegDispatchRes) XXX_Size() int {
	return xxx_messageInfo_RegDispatchRes.Size(m)
}
func (m *RegDispatchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegDispatchRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegDispatchRes proto.InternalMessageInfo

func (m *RegDispatchRes) GetIRet() int32 {
	if m != nil {
		return m.IRet
	}
	return 0
}

func init() {
	proto.RegisterType((*Head)(nil), "innermsg.Head")
	proto.RegisterType((*NetHead)(nil), "innermsg.NetHead")
	proto.RegisterType((*MsgBody)(nil), "innermsg.MsgBody")
	proto.RegisterType((*ClientBody)(nil), "innermsg.ClientBody")
	proto.RegisterType((*InnerMsgForDB)(nil), "innermsg.InnerMsgForDB")
	proto.RegisterType((*RegDispatch)(nil), "innermsg.RegDispatch")
	proto.RegisterType((*RegDispatchRes)(nil), "innermsg.RegDispatchRes")
}

func init() { proto.RegisterFile("InnerMsg.proto", fileDescriptor_5b62ec459e15f753) }

var fileDescriptor_5b62ec459e15f753 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xdb, 0xae, 0x12, 0x31,
	0x14, 0xcd, 0x1c, 0x66, 0x18, 0x66, 0x73, 0x86, 0x68, 0x63, 0x4c, 0xe3, 0x83, 0xd1, 0x89, 0x26,
	0x3e, 0xf1, 0xa0, 0x5f, 0xe0, 0x39, 0x04, 0xe5, 0x41, 0x1e, 0x8a, 0x3f, 0x30, 0xd0, 0x32, 0x4c,
	0xc2, 0x5c, 0x32, 0xad, 0x17, 0x3e, 0xc5, 0x4f, 0xf0, 0x27, 0xfc, 0x36, 0xbb, 0x77, 0x5b, 0xc0,
	0x68, 0xcc, 0x79, 0x62, 0xad, 0xd5, 0xbd, 0x36, 0x8b, 0xd5, 0x02, 0xb3, 0x55, 0xdb, 0xaa, 0xe1,
	0x93, 0xae, 0xe6, 0xfd, 0xd0, 0x99, 0x8e, 0x4d, 0x6a, 0xe4, 0x8d, 0xae, 0x8a, 0x5f, 0x37, 0x10,
	0x7f, 0x54, 0xa5, 0x64, 0x8f, 0x60, 0xf4, 0xa5, 0x96, 0x3c, 0x7a, 0x11, 0xbd, 0x49, 0x04, 0x42,
	0x54, 0x76, 0x8d, 0xe4, 0x37, 0x56, 0xc9, 0x05, 0x42, 0xf6, 0x1c, 0xc0, 0x0c, 0x65, 0xab, 0x3f,
	0x9f, 0x7a, 0xa5, 0xf9, 0x88, 0x46, 0xaf, 0x14, 0xc6, 0x21, 0xb5, 0x3b, 0x11, 0xf3, 0x98, 0x5c,
	0x81, 0xb2, 0xa7, 0x30, 0xd6, 0x1b, 0x35, 0xac, 0x24, 0x4f, 0xc8, 0xe5, 0x19, 0x7b, 0x06, 0x13,
	0x44, 0x64, 0x19, 0xd3, 0xc9, 0x99, 0xa3, 0x47, 0x3a, 0x4f, 0xea, 0x3c, 0xf2, 0xec, 0x91, 0xc1,
	0x33, 0x71, 0x9e, 0xc0, 0xf1, 0xcc, 0xd8, 0xcf, 0x75, 0xd9, 0x28, 0x9e, 0xd9, 0xb3, 0x4c, 0x9c,
	0x39, 0x7b, 0x02, 0x89, 0xde, 0x1f, 0xbb, 0x6f, 0x1c, 0xc8, 0xe4, 0x08, 0xaa, 0x92, 0xd4, 0xa9,
	0x53, 0x89, 0xe0, 0x6f, 0xd7, 0xab, 0x9e, 0xdf, 0xd2, 0x0a, 0x84, 0x98, 0xa6, 0xb2, 0x5b, 0x6c,
	0x9a, 0xdc, 0xa5, 0x71, 0xac, 0xf8, 0x11, 0x41, 0xba, 0x56, 0xe6, 0xc1, 0x1d, 0x5e, 0xf6, 0x8c,
	0x48, 0xf4, 0x8c, 0x31, 0x88, 0xf7, 0xc7, 0xb2, 0xa2, 0xe2, 0x32, 0x41, 0x18, 0xfb, 0xfc, 0xaa,
	0x06, 0x5d, 0x77, 0x2d, 0xd5, 0x96, 0x89, 0x40, 0x71, 0x7a, 0xd7, 0x49, 0xd7, 0x59, 0x2e, 0x08,
	0xe3, 0x77, 0xa9, 0xef, 0x86, 0xca, 0xb2, 0x99, 0x2d, 0x2c, 0xde, 0x43, 0x6a, 0xef, 0xfc, 0xae,
	0x93, 0x27, 0x56, 0x40, 0x7c, 0xb0, 0x11, 0x29, 0xdb, 0xf4, 0xed, 0x6c, 0x1e, 0x1e, 0xc0, 0x1c,
	0x83, 0x0b, 0x3a, 0xc3, 0xa5, 0x5b, 0x3b, 0x4b, 0x69, 0x6f, 0x05, 0xe1, 0xe2, 0x03, 0xc0, 0xfd,
	0xb1, 0x56, 0xad, 0xa1, 0x2d, 0xaf, 0xff, 0xd8, 0xf2, 0xf8, 0xb2, 0xc5, 0x37, 0xf0, 0x9f, 0x45,
	0x3f, 0x23, 0xc8, 0xc3, 0x2b, 0x5c, 0x76, 0xc3, 0xe2, 0x0e, 0x9b, 0xe8, 0x07, 0x75, 0xdf, 0x84,
	0xc2, 0x3c, 0xf3, 0xfa, 0xa6, 0x76, 0xb5, 0x39, 0xdd, 0xb2, 0xa0, 0x9b, 0xde, 0xbf, 0x3c, 0xcf,
	0xb0, 0x25, 0x8b, 0x96, 0x78, 0x87, 0x31, 0x1d, 0x04, 0x1a, 0xee, 0x23, 0xf9, 0xeb, 0x3e, 0xdc,
	0x53, 0xa3, 0xfb, 0x08, 0x59, 0xd3, 0xab, 0xac, 0x2f, 0x61, 0x2a, 0x54, 0xb5, 0xa8, 0x75, 0x5f,
	0x9a, 0xdd, 0x01, 0x47, 0x6a, 0xa1, 0x8c, 0x8f, 0x49, 0xb8, 0x78, 0x05, 0xb3, 0xab, 0x11, 0x61,
	0x1f, 0xff, 0x3f, 0xa6, 0xb6, 0x63, 0xfa, 0xbb, 0xbd, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0x82, 0x5e, 0xf3, 0x80, 0x03, 0x00, 0x00,
}
