// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/access.proto

package globby

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// client 登录请求消息
type CmdLoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	HeadUrl              string   `protobuf:"bytes,4,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	HeadId               int32    `protobuf:"varint,5,opt,name=headId,proto3" json:"headId,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	OsType               int32    `protobuf:"varint,7,opt,name=osType,proto3" json:"osType,omitempty"`
	LoginType            int32    `protobuf:"varint,8,opt,name=loginType,proto3" json:"loginType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdLoginRequest) Reset()         { *m = CmdLoginRequest{} }
func (m *CmdLoginRequest) String() string { return proto.CompactTextString(m) }
func (*CmdLoginRequest) ProtoMessage()    {}
func (*CmdLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{0}
}

func (m *CmdLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdLoginRequest.Unmarshal(m, b)
}
func (m *CmdLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdLoginRequest.Marshal(b, m, deterministic)
}
func (m *CmdLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdLoginRequest.Merge(m, src)
}
func (m *CmdLoginRequest) XXX_Size() int {
	return xxx_messageInfo_CmdLoginRequest.Size(m)
}
func (m *CmdLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CmdLoginRequest proto.InternalMessageInfo

func (m *CmdLoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CmdLoginRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *CmdLoginRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CmdLoginRequest) GetHeadUrl() string {
	if m != nil {
		return m.HeadUrl
	}
	return ""
}

func (m *CmdLoginRequest) GetHeadId() int32 {
	if m != nil {
		return m.HeadId
	}
	return 0
}

func (m *CmdLoginRequest) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *CmdLoginRequest) GetOsType() int32 {
	if m != nil {
		return m.OsType
	}
	return 0
}

func (m *CmdLoginRequest) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

// ser 返回登录请求消息
type CmdLoginResponse struct {
	ErrType              int32    `protobuf:"varint,1,opt,name=errType,proto3" json:"errType,omitempty"`
	ErrInfo              string   `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	Uid                  int32    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Diamond              int64    `protobuf:"varint,4,opt,name=diamond,proto3" json:"diamond,omitempty"`
	Card                 int64    `protobuf:"varint,5,opt,name=card,proto3" json:"card,omitempty"`
	Coin                 int64    `protobuf:"varint,6,opt,name=coin,proto3" json:"coin,omitempty"`
	Nickname             string   `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	HeadUrl              string   `protobuf:"bytes,8,opt,name=headUrl,proto3" json:"headUrl,omitempty"`
	HeadId               int32    `protobuf:"varint,9,opt,name=headId,proto3" json:"headId,omitempty"`
	Sex                  int32    `protobuf:"varint,10,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdLoginResponse) Reset()         { *m = CmdLoginResponse{} }
func (m *CmdLoginResponse) String() string { return proto.CompactTextString(m) }
func (*CmdLoginResponse) ProtoMessage()    {}
func (*CmdLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{1}
}

func (m *CmdLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdLoginResponse.Unmarshal(m, b)
}
func (m *CmdLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdLoginResponse.Marshal(b, m, deterministic)
}
func (m *CmdLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdLoginResponse.Merge(m, src)
}
func (m *CmdLoginResponse) XXX_Size() int {
	return xxx_messageInfo_CmdLoginResponse.Size(m)
}
func (m *CmdLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CmdLoginResponse proto.InternalMessageInfo

func (m *CmdLoginResponse) GetErrType() int32 {
	if m != nil {
		return m.ErrType
	}
	return 0
}

func (m *CmdLoginResponse) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *CmdLoginResponse) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CmdLoginResponse) GetDiamond() int64 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *CmdLoginResponse) GetCard() int64 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *CmdLoginResponse) GetCoin() int64 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *CmdLoginResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CmdLoginResponse) GetHeadUrl() string {
	if m != nil {
		return m.HeadUrl
	}
	return ""
}

func (m *CmdLoginResponse) GetHeadId() int32 {
	if m != nil {
		return m.HeadId
	}
	return 0
}

func (m *CmdLoginResponse) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// game server 上报游戏服务器房间信息
type GSerRoomInfo struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	TableType            int32    `protobuf:"varint,3,opt,name=tableType,proto3" json:"tableType,omitempty"`
	ShowTableId          int32    `protobuf:"varint,4,opt,name=showTableId,proto3" json:"showTableId,omitempty"`
	OwnId                int32    `protobuf:"varint,5,opt,name=ownId,proto3" json:"ownId,omitempty"`
	TotalGameNum         int32    `protobuf:"varint,6,opt,name=totalGameNum,proto3" json:"totalGameNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GSerRoomInfo) Reset()         { *m = GSerRoomInfo{} }
func (m *GSerRoomInfo) String() string { return proto.CompactTextString(m) }
func (*GSerRoomInfo) ProtoMessage()    {}
func (*GSerRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{2}
}

func (m *GSerRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GSerRoomInfo.Unmarshal(m, b)
}
func (m *GSerRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GSerRoomInfo.Marshal(b, m, deterministic)
}
func (m *GSerRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GSerRoomInfo.Merge(m, src)
}
func (m *GSerRoomInfo) XXX_Size() int {
	return xxx_messageInfo_GSerRoomInfo.Size(m)
}
func (m *GSerRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GSerRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GSerRoomInfo proto.InternalMessageInfo

func (m *GSerRoomInfo) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *GSerRoomInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GSerRoomInfo) GetTableType() int32 {
	if m != nil {
		return m.TableType
	}
	return 0
}

func (m *GSerRoomInfo) GetShowTableId() int32 {
	if m != nil {
		return m.ShowTableId
	}
	return 0
}

func (m *GSerRoomInfo) GetOwnId() int32 {
	if m != nil {
		return m.OwnId
	}
	return 0
}

func (m *GSerRoomInfo) GetTotalGameNum() int32 {
	if m != nil {
		return m.TotalGameNum
	}
	return 0
}

type CmdReportSerRooms struct {
	GameId               int32           `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	ServId               int32           `protobuf:"varint,2,opt,name=servId,proto3" json:"servId,omitempty"`
	SerLevel             int32           `protobuf:"varint,3,opt,name=serLevel,proto3" json:"serLevel,omitempty"`
	MaxUserCount         int32           `protobuf:"varint,4,opt,name=maxUserCount,proto3" json:"maxUserCount,omitempty"`
	MaxTableCount        int32           `protobuf:"varint,5,opt,name=maxTableCount,proto3" json:"maxTableCount,omitempty"`
	TotalUserCount       int32           `protobuf:"varint,6,opt,name=totalUserCount,proto3" json:"totalUserCount,omitempty"`
	Rooms                []*GSerRoomInfo `protobuf:"bytes,7,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CmdReportSerRooms) Reset()         { *m = CmdReportSerRooms{} }
func (m *CmdReportSerRooms) String() string { return proto.CompactTextString(m) }
func (*CmdReportSerRooms) ProtoMessage()    {}
func (*CmdReportSerRooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{3}
}

func (m *CmdReportSerRooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdReportSerRooms.Unmarshal(m, b)
}
func (m *CmdReportSerRooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdReportSerRooms.Marshal(b, m, deterministic)
}
func (m *CmdReportSerRooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdReportSerRooms.Merge(m, src)
}
func (m *CmdReportSerRooms) XXX_Size() int {
	return xxx_messageInfo_CmdReportSerRooms.Size(m)
}
func (m *CmdReportSerRooms) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdReportSerRooms.DiscardUnknown(m)
}

var xxx_messageInfo_CmdReportSerRooms proto.InternalMessageInfo

func (m *CmdReportSerRooms) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *CmdReportSerRooms) GetServId() int32 {
	if m != nil {
		return m.ServId
	}
	return 0
}

func (m *CmdReportSerRooms) GetSerLevel() int32 {
	if m != nil {
		return m.SerLevel
	}
	return 0
}

func (m *CmdReportSerRooms) GetMaxUserCount() int32 {
	if m != nil {
		return m.MaxUserCount
	}
	return 0
}

func (m *CmdReportSerRooms) GetMaxTableCount() int32 {
	if m != nil {
		return m.MaxTableCount
	}
	return 0
}

func (m *CmdReportSerRooms) GetTotalUserCount() int32 {
	if m != nil {
		return m.TotalUserCount
	}
	return 0
}

func (m *CmdReportSerRooms) GetRooms() []*GSerRoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

// 客户端请求创建房间
type CmdRequestCreateRoom struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Param                string   `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	Rule                 string   `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdRequestCreateRoom) Reset()         { *m = CmdRequestCreateRoom{} }
func (m *CmdRequestCreateRoom) String() string { return proto.CompactTextString(m) }
func (*CmdRequestCreateRoom) ProtoMessage()    {}
func (*CmdRequestCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{4}
}

func (m *CmdRequestCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdRequestCreateRoom.Unmarshal(m, b)
}
func (m *CmdRequestCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdRequestCreateRoom.Marshal(b, m, deterministic)
}
func (m *CmdRequestCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdRequestCreateRoom.Merge(m, src)
}
func (m *CmdRequestCreateRoom) XXX_Size() int {
	return xxx_messageInfo_CmdRequestCreateRoom.Size(m)
}
func (m *CmdRequestCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdRequestCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CmdRequestCreateRoom proto.InternalMessageInfo

func (m *CmdRequestCreateRoom) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *CmdRequestCreateRoom) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *CmdRequestCreateRoom) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

// 客户端请求加入房间
type CmdRequestJoinRoom struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdRequestJoinRoom) Reset()         { *m = CmdRequestJoinRoom{} }
func (m *CmdRequestJoinRoom) String() string { return proto.CompactTextString(m) }
func (*CmdRequestJoinRoom) ProtoMessage()    {}
func (*CmdRequestJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{5}
}

func (m *CmdRequestJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdRequestJoinRoom.Unmarshal(m, b)
}
func (m *CmdRequestJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdRequestJoinRoom.Marshal(b, m, deterministic)
}
func (m *CmdRequestJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdRequestJoinRoom.Merge(m, src)
}
func (m *CmdRequestJoinRoom) XXX_Size() int {
	return xxx_messageInfo_CmdRequestJoinRoom.Size(m)
}
func (m *CmdRequestJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdRequestJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CmdRequestJoinRoom proto.InternalMessageInfo

func (m *CmdRequestJoinRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 客户端创建加入房间返回消息
type CmdCrtJonRoomResponse struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdCrtJonRoomResponse) Reset()         { *m = CmdCrtJonRoomResponse{} }
func (m *CmdCrtJonRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CmdCrtJonRoomResponse) ProtoMessage()    {}
func (*CmdCrtJonRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d521d356a48de6, []int{6}
}

func (m *CmdCrtJonRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdCrtJonRoomResponse.Unmarshal(m, b)
}
func (m *CmdCrtJonRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdCrtJonRoomResponse.Marshal(b, m, deterministic)
}
func (m *CmdCrtJonRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdCrtJonRoomResponse.Merge(m, src)
}
func (m *CmdCrtJonRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CmdCrtJonRoomResponse.Size(m)
}
func (m *CmdCrtJonRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdCrtJonRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CmdCrtJonRoomResponse proto.InternalMessageInfo

func (m *CmdCrtJonRoomResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*CmdLoginRequest)(nil), "globby.CmdLoginRequest")
	proto.RegisterType((*CmdLoginResponse)(nil), "globby.CmdLoginResponse")
	proto.RegisterType((*GSerRoomInfo)(nil), "globby.GSerRoomInfo")
	proto.RegisterType((*CmdReportSerRooms)(nil), "globby.CmdReportSerRooms")
	proto.RegisterType((*CmdRequestCreateRoom)(nil), "globby.CmdRequestCreateRoom")
	proto.RegisterType((*CmdRequestJoinRoom)(nil), "globby.CmdRequestJoinRoom")
	proto.RegisterType((*CmdCrtJonRoomResponse)(nil), "globby.CmdCrtJonRoomResponse")
}

func init() { proto.RegisterFile("pb/access.proto", fileDescriptor_b0d521d356a48de6) }

var fileDescriptor_b0d521d356a48de6 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xd4, 0x3c,
	0x10, 0x55, 0xbe, 0x6d, 0xf6, 0x67, 0xda, 0x8f, 0x16, 0x6b, 0x41, 0x11, 0xe2, 0xa2, 0x8a, 0x10,
	0xaa, 0x10, 0x5a, 0x04, 0x3c, 0x42, 0x2e, 0xaa, 0xa0, 0x8a, 0x8b, 0xd0, 0x4a, 0xdc, 0x3a, 0x1b,
	0xb3, 0x8d, 0x48, 0xe2, 0x60, 0x3b, 0xdd, 0xf6, 0xb5, 0x78, 0x1b, 0x5e, 0x05, 0x09, 0x09, 0xcf,
	0xd8, 0x49, 0x76, 0x2b, 0xf6, 0x6e, 0xce, 0x99, 0x93, 0xd9, 0x73, 0xc6, 0xf6, 0xc2, 0x69, 0x9b,
	0xbf, 0xe3, 0xeb, 0xb5, 0xd0, 0x7a, 0xd5, 0x2a, 0x69, 0x24, 0x9b, 0x6e, 0x2a, 0x99, 0xe7, 0x0f,
	0xf1, 0xaf, 0x00, 0x4e, 0x93, 0xba, 0xb8, 0x92, 0x9b, 0xb2, 0xc9, 0xc4, 0x8f, 0x4e, 0x68, 0xc3,
	0x22, 0x98, 0x59, 0xad, 0xec, 0x1a, 0x13, 0x05, 0xe7, 0xc1, 0xc5, 0x22, 0xeb, 0x21, 0x7b, 0x0e,
	0xd3, 0x96, 0x6b, 0xbd, 0x2d, 0xa2, 0xff, 0xa8, 0xe1, 0x11, 0x7b, 0x01, 0xf3, 0xa6, 0x5c, 0x7f,
	0x6f, 0x78, 0x2d, 0xa2, 0x09, 0x75, 0x06, 0x8c, 0xd3, 0x6e, 0x05, 0x2f, 0x6e, 0x54, 0x15, 0x1d,
	0xb9, 0x69, 0x1e, 0xe2, 0x34, 0x2c, 0xd3, 0x22, 0x0a, 0x6d, 0x23, 0xcc, 0x3c, 0x62, 0x67, 0x30,
	0xd1, 0xe2, 0x3e, 0x9a, 0x12, 0x89, 0x25, 0x2a, 0xa5, 0xbe, 0x7e, 0x68, 0x45, 0x34, 0x73, 0x4a,
	0x87, 0xd8, 0x4b, 0x58, 0x54, 0xe8, 0x9c, 0x5a, 0x73, 0x6a, 0x8d, 0x44, 0xfc, 0x3b, 0x80, 0xb3,
	0x31, 0x9b, 0x6e, 0x65, 0xa3, 0xc9, 0x8e, 0x50, 0x8a, 0x3e, 0x08, 0xe8, 0x83, 0x1e, 0xfa, 0x4e,
	0xda, 0x7c, 0x93, 0x3e, 0x5d, 0x0f, 0xd1, 0x50, 0x57, 0x16, 0x94, 0xcc, 0x1a, 0xb2, 0x25, 0x6a,
	0x8b, 0x92, 0xd7, 0xb2, 0x29, 0x28, 0xd4, 0x24, 0xeb, 0x21, 0x63, 0x70, 0xb4, 0xe6, 0xca, 0x45,
	0x9a, 0x64, 0x54, 0x13, 0x27, 0xcb, 0x86, 0x12, 0x21, 0x67, 0xeb, 0xbd, 0x95, 0xcd, 0x0e, 0xaf,
	0x6c, 0x7e, 0x68, 0x65, 0x8b, 0x7f, 0xad, 0x0c, 0x86, 0x95, 0xc5, 0x3f, 0x03, 0x38, 0xb9, 0xfc,
	0x22, 0x54, 0x26, 0x65, 0xdd, 0x87, 0x30, 0x36, 0x84, 0x0b, 0x8d, 0x25, 0x0e, 0xd3, 0x86, 0x9b,
	0x4e, 0x53, 0x5e, 0x3b, 0xcc, 0x21, 0xdc, 0xaa, 0xe1, 0x79, 0x25, 0x68, 0x49, 0x2e, 0xf4, 0x48,
	0xb0, 0x73, 0x38, 0xd6, 0xb7, 0x72, 0x7b, 0x8d, 0x44, 0xea, 0xe2, 0x87, 0xd9, 0x2e, 0xc5, 0x96,
	0x10, 0xca, 0x6d, 0x33, 0x1c, 0xab, 0x03, 0x2c, 0x86, 0x13, 0x23, 0x0d, 0xaf, 0x2e, 0x6d, 0xc2,
	0xcf, 0x5d, 0xed, 0x8f, 0x77, 0x8f, 0x8b, 0xff, 0x04, 0xf0, 0xd4, 0x9e, 0x58, 0x26, 0x5a, 0xa9,
	0x8c, 0x37, 0xaf, 0xd1, 0xe7, 0xc6, 0x0a, 0xd2, 0xde, 0xbc, 0x47, 0xe4, 0x5f, 0xa8, 0xbb, 0xb4,
	0x18, 0xfc, 0x13, 0xc2, 0xd5, 0xda, 0xea, 0x4a, 0xdc, 0x89, 0xca, 0xdb, 0x1f, 0x30, 0xba, 0xa8,
	0xf9, 0xfd, 0x8d, 0xc5, 0x09, 0x5d, 0x70, 0x67, 0x7f, 0x8f, 0x63, 0xaf, 0xe0, 0x7f, 0x8b, 0x29,
	0x8d, 0x13, 0xb9, 0x1c, 0xfb, 0x24, 0x7b, 0x0d, 0x4f, 0xc8, 0xfb, 0x38, 0xcb, 0x25, 0x7a, 0xc4,
	0xb2, 0x37, 0x10, 0x2a, 0x8c, 0x61, 0x4f, 0x79, 0x72, 0x71, 0xfc, 0x61, 0xb9, 0x72, 0x2f, 0x6f,
	0xb5, 0x7b, 0x38, 0x99, 0x93, 0xc4, 0x5f, 0x61, 0x49, 0xf1, 0xe9, 0x1d, 0x26, 0x4a, 0x70, 0x23,
	0x50, 0x72, 0x70, 0x03, 0x76, 0xd3, 0x2d, 0x57, 0xbc, 0xf6, 0x17, 0xd6, 0x01, 0xbc, 0x6e, 0xaa,
	0xab, 0xfa, 0x97, 0x48, 0x75, 0xfc, 0x16, 0xd8, 0x38, 0xf9, 0x93, 0xbd, 0x80, 0xfd, 0x5c, 0xfc,
	0xe1, 0x71, 0xae, 0x43, 0xf1, 0x7b, 0x78, 0x66, 0xd5, 0x89, 0xb2, 0x4a, 0x12, 0x3e, 0x7a, 0x3d,
	0x89, 0x2c, 0x76, 0x5f, 0x0f, 0xc2, 0x7c, 0x4a, 0xff, 0x2b, 0x1f, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0xb5, 0x38, 0xe1, 0x6a, 0x04, 0x00, 0x00,
}
